name: restlib_parsing
description: Parsec style parsers for dart.
dependencies: 
  restlib_common:
    git: https://code.google.com/p/dart-restlib.common/
dev_dependencies:
  restlib_testing:
    git: https://code.google.com/p/dart-restlib.testing/
  unittest: any
